
package com.compuware.identity.authentication.repo.jira.webservice.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LoginWebservice", targetNamespace = "http://login.webservice.dtmanager.dynatrace.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginWebservice {


    /**
     * 
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://login.webservice.dtmanager.dynatrace.com/", className = "com.compuware.identity.authentication.repo.jira.webservice.login.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://login.webservice.dtmanager.dynatrace.com/", className = "com.compuware.identity.authentication.repo.jira.webservice.login.LoginResponse")
    public String login(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://login.webservice.dtmanager.dynatrace.com/", className = "com.compuware.identity.authentication.repo.jira.webservice.login.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://login.webservice.dtmanager.dynatrace.com/", className = "com.compuware.identity.authentication.repo.jira.webservice.login.LogoutResponse")
    public boolean logout(
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.compuware.identity.authentication.repo.jira.webservice.login.SessionToken
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginRest", targetNamespace = "http://login.webservice.dtmanager.dynatrace.com/", className = "com.compuware.identity.authentication.repo.jira.webservice.login.LoginRest")
    @ResponseWrapper(localName = "loginRestResponse", targetNamespace = "http://login.webservice.dtmanager.dynatrace.com/", className = "com.compuware.identity.authentication.repo.jira.webservice.login.LoginRestResponse")
    public SessionToken loginRest(
        @WebParam(name = "arg0", targetNamespace = "")
        LoginCredentials arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logoutRest", targetNamespace = "http://login.webservice.dtmanager.dynatrace.com/", className = "com.compuware.identity.authentication.repo.jira.webservice.login.LogoutRest")
    @ResponseWrapper(localName = "logoutRestResponse", targetNamespace = "http://login.webservice.dtmanager.dynatrace.com/", className = "com.compuware.identity.authentication.repo.jira.webservice.login.LogoutRestResponse")
    public String logoutRest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
